# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: leo
email: leo2vip@sina.com
description:  Today, give a stranger one of your smiles. It might be the only sunshine he sees all day.
baseurl: "" # the subpath of your site, e.g. /blog    /leo2vip.github.com
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
